[ {
  "id" : 74,
  "fullName" : "Chris Hemsworth",
  "phones" : [ "+380671111111", "+380672222222" ],
  "emails" : [ "chris.h@m.ua", "chris.h@gmail.com" ],
  "githubId" : "ChrisHemGit"
}, {
  "id" : 5736,
  "fullName" : "Chris Pratt",
  "phones" : [ "+380673333333", "+380674444444" ],
  "emails" : [ "chris.p@m.ua", "chris.p@gmail.com" ],
  "githubId" : "ChrisPraGit"
}, {
  "id" : 7070,
  "fullName" : "Scarlett Johansson",
  "phones" : [ "+380675555555", "+380676666666" ],
  "emails" : [ "Scarlett.j@m.ua", "Scarlett.j@gmail.com" ],
  "githubId" : "ScarlettJohGit"
}, {
  "id" : 7160,
  "fullName" : "Jeremy Renner",
  "phones" : [ "+380677777777", "+380678888888" ],
  "emails" : [ "Jeremy.r@m.ua", "Jeremy.r@gmail.com" ],
  "githubId" : "JeremyRenGit"
} ]